botfront/botfront

botfront/imports/api/instances/instances.schema.js
botfront/imports/ui/components/nlu/instances/Instances.jsx

Remove the admin only property on the instance model.
I made sure to

fix: removed useles instance property

---

botfront/client/main.less
botfront/imports/ui/layouts/account.jsx

Made the login background image full size
I made sure to

fix: login background size

---

botfront/.env

The subscription email was wrong, I fixed it. 
I made sure to

fix: subscription email

---

botfront/docs/guide/getting-started/quick-start.md
botfront/docs/guide/getting-started/rasa-stack.md
botfront/docs/guide/nlu/instances-models.md
botfront/docs/guide/users/endpoints.md
botfront/imports/api/instances/instances.docker-compose.js
botfront/private/default-settings.docker-compose.json

changed docker host resolution to rely on docker dns rather than going through localhost
I made sure to

fix: linux compatibility

---

Dockerfile
entrypoint.sh

startup failed because it could not connect to mongo database, wrote a custom script to fix the issue
I made sure to

fix: docker compose

---

botfront/imports/ui/components/project/ProjectSidebar.jsx

ui: changed support icon

---

botfront/imports/ui/components/nlu/models/NLUModel.jsx

Added dynamic import for moment timezone module

optimize(loadtime)

---

botfront/docs/guide/users/settings.md

Type-o fix

---

botfront/docs/guide/getting-started/quick-start.md
botfront/docs/guide/nlu/instances-models.md

Misc updates

---

botfront/imports/ui/components/nlu/models/IntentBulkInsert.jsx

Added a message on adding intent, in bulk insert

chore(bulk-insert): Added a tip to create/add an intent

---

botfront/cypress/integration/docker-compose/docker-compose.spec.js
botfront/imports/api/endpoints/endpoints.methods.js
botfront/imports/api/globalSettings/globalSettings.collection.js
botfront/imports/api/instances/instances.methods.js
botfront/imports/api/orchestration/orchestration.methods.js
botfront/imports/api/project/project.collection.js
botfront/imports/api/setup.js

Looked for process.env variable across the project and added the default as docker-compose where-ever necessary

chore(default-orchetrator): Made docker-compose as the default orchestrator

---

botfront/imports/ui/components/nlu/import-export/DeleteModel.jsx
botfront/imports/ui/components/nlu/models/NLUModel.jsx

refactor(delete-language): Added language prop to delete model

---

.gitignore
botfront/private/default-settings.docker-compose.json
botfront/private/default-settings.json

Amended commit since last one had introduced broken yaml.

chore: changed default settings; removed then() in getMissingImgs func

---

botfront/imports/lib/nlu_methods.js
botfront/imports/ui/components/nlu/import-export/DataImport.jsx
botfront/imports/ui/components/nlu/models/NLUModel.jsx

I made sure that the data imports test passes

feat(data-import): uploaded file is converted to json by rasa endpoint

---

botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/models/NLUModel.jsx

Activities component was not passing the example correctly to the rasa.parse method, fixed it.
I made sure to

fix(activity): Fixed language field from models

---

botfront/docs/.vuepress/config.js
botfront/docs/README.md
botfront/docs/guide/getting-started/branching-conversations.md
botfront/docs/guide/getting-started/quick-start.md
botfront/docs/guide/getting-started/setup.md

I made sure to
- [X ] document the feature if needed

Better tutorial on stories and slots

---

botfront/imports/api/activity.js
botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/activity/ActivityDataTable.jsx
botfront/imports/ui/components/nlu/evaluation/Evaluation.jsx

To go along with API change.
All Cypress tests pass.

refactor(activity table): fix transition to evaluations

---

botfront/docs/guide/README.md

Fixed typos

---

botfront/imports/api/activity.js
botfront/imports/api/instances/instances.methods.js
botfront/imports/lib/utils.js
botfront/imports/ui/components/example_editor/Entity.jsx
botfront/imports/ui/components/nlu/activity/ActivityDataTable.jsx
botfront/imports/ui/components/nlu/activity/SmartTip.jsx
botfront/imports/ui/components/nlu/models/IntentViewer.jsx
botfront/imports/ui/components/nlu/models/NluDataTable.jsx
botfront/imports/ui/components/synonyms/LookupTable.jsx

DataTables fixes and feats

---

botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/utils/TrainButton.jsx

chore(story-group): Fixed typo

---

botfront/docs/guide/users-guide/branching-conversations.md

Fixed typo in the docs

---

botfront/imports/api/slots/slots.collection.js
botfront/imports/api/slots/slots.methods.js

unique slot names, throws an error if slot name already exists

feat: unique slot names

---

botfront/.storybook/webpack.config.js
botfront/package-lock.json
botfront/package.json

added support for less css preprocessor in storybook

refactor: added less support to storybook

---

botfront/package-lock.json
botfront/package.json

Apart from the update a small bug was fixed in the stories test, which was found in the ee version. It has been already fixed there. A test on train button is failing and because of it test in stories also fail, but fix is already present in another pull request.

chore(update-dependencies): Updated babel and removed vulnerabilities

---

botfront/imports/ui/components/utils/UtteranceInput.jsx
botfront/stories/UtteranceInout.stories.js
botfront/stories/UtteranceInput.stories.js

feat(utterance-input):  Add utterance input

---

botfront/docs/guide/developers-guide/README.md

Since we're using meteor, all `npm` and `npx` commands should be prefixed with `meteor`
I made sure to

Update README.md to use meteor

---

botfront/imports/ui/components/utils/EntityLabel.jsx
botfront/imports/ui/components/utils/UserUtteranceViewer.jsx
botfront/stories/UtteranceViewer.stories.js
botfront/stories/entity.stories.js

fix(utterance-viewer): fix entity recall logic

---

botfront/imports/ui/components/utils/UserUtteranceViewer.jsx
botfront/imports/ui/components/utils/style/style.import.less
botfront/stories/UtteranceViewer.stories.js

refactor: added tagging to utteranceViewer

---

botfront/cypress/docker-compose.yml
botfront/cypress/package-lock.json
botfront/cypress/package.json
botfront/package-lock.json
botfront/package.json
cloudbuild.yaml

chore(deps): update cypress

---

botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/api/storyGroups/storyGroups.methods.js

Removed unnecessary code for nlu models

refactor(nlu-model): remove reduntant code

---

botfront/docs/guide/developers-guide/README.md
botfront/docs/guide/getting-started/setup.md
botfront/private/default-settings.docker-compose.dev.json

feat: easier setup to develop against the docker-compose stack

---

botfront/imports/api/instances/instances.collection.js
botfront/imports/api/instances/instances.schema.js
botfront/imports/lib/nlu_methods.js
botfront/imports/ui/components/example_editor/NLUExampleTester.jsx
botfront/imports/ui/components/nlu/models/API.jsx
botfront/private/default-settings.docker-compose.dev.json
botfront/private/default-settings.docker-compose.json
botfront/private/default-settings.json

refactor(instance): remove redundancy code

---

botfront/cypress/integration/chat/chat.spec.js
botfront/imports/api/instances/instances.methods.js
botfront/imports/api/project/project.methods.js
botfront/imports/api/story/stories.methods.js
botfront/imports/api/story/stories.schema.js
botfront/imports/ui/components/project/ProjectChat.jsx
botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/StoriesEditor.jsx
botfront/imports/ui/components/stories/StoryAceEditor.jsx

refactor: allow empty stories

---

botfront/cypress/integration/01_initial_setup_dont_change_name/initial_setup.spec.js
botfront/imports/ui/components/index.jsx
botfront/imports/ui/components/project/ProjectSidebar.jsx
botfront/imports/ui/components/setup/SetupSteps.jsx

Also, in the sidebar stories are on the top, followed by NLU

chore(default-route): stories are default route in a project

---

botfront/cypress/integration/accessibility/scrolling.spec.js
botfront/cypress/support/index.js
botfront/imports/api/project/project.methods.js

- [ X] I wrote tests for the feature

refactor: group project.delete args in options object

---

botfront/imports/ui/components/project/ProjectChat.jsx

unique payload for chat initial stories

refactor: unique payloads initial story

---

botfront/cypress/integration/nlu_models/nlu_intentmessage.spec.js
botfront/imports/ui/components/nlu/models/NLUModel.jsx

this feature is not a refactor

feat: add warning when NLU can't be trained because of  n < 2 intents

---

botfront/cypress/integration/stories/persist-state.spec.js

added tests for state persistence in story tab

test: story-state-persistence

---

botfront/cypress/integration/stories/default_story_group.spec.js
botfront/imports/api/project/project.methods.js
botfront/imports/api/storyGroups/storyGroups.methods.js

Default story group

---

botfront/imports/ui/components/stories/BranchTabLabel.jsx
botfront/imports/ui/components/stories/style.import.less
botfront/stories/BranchTabLabel.stories.js

- I created a BranchTabLabel component for the branch menu
- I created a story to verify the component works as expected
- I added necessary styling to the component in style.import.less

feat: add branch tab component for branch menu

---

botfront/imports/ui/components/stories/StoryEditorContainer.jsx
botfront/imports/ui/components/stories/StoryFooter.jsx
botfront/imports/ui/components/stories/StoryPathPopup.jsx
botfront/imports/ui/components/stories/style.import.less
botfront/stories/StoryFooter.stories.js

Story bottom menu

---

botfront/cypress/integration/stories/branches.spec.js
botfront/imports/ui/components/stories/BranchTabLabel.jsx
botfront/imports/ui/components/stories/StoryEditorContainer.jsx

I wrote a test for branching that checks if:
-  a third branch can be created with the add branch button
- a branch can be deleted
- if a branch is deleted when only two branches exist it will warn the user and then delete both branches

test: new for add 3rd branch and delete branches

---

botfront/imports/api/project/project.methods.js
botfront/imports/lib/story.utils.js
botfront/imports/lib/story_controller.js
botfront/imports/lib/story_controller.tests.js

prepare domain for disambiguation policy

---

cli/project-template/.botfront/botfront.yml
cli/project-template/.botfront/docker-compose-template.yml
cli/project-template/actions/__init__.py

chore: remove dependency on botfront sdk image

---

botfront/docs/.vuepress/config.js
botfront/imports/ui/components/project/ProjectSidebar.jsx
botfront/private/default-settings.docker-compose.json

docs: links to Spectrum in menu and docs

---

botfront/private/default-settings.docker-compose.json

fix: wrong default base_url in credentials

---

cli/project-template/.botfront/docker-compose-template.yml

fix: typo in docker compose template

---

botfront/imports/api/story/stories.schema.js
botfront/imports/api/storyGroups/storyGroups.methods.js
botfront/imports/api/storyGroups/storyGroups.schema.js
botfront/imports/lib/story.utils.js
botfront/imports/lib/story_controller.js
botfront/imports/ui/components/common/Browser.jsx
botfront/imports/ui/components/stories/BranchTabLabel.jsx
botfront/imports/ui/components/stories/ExceptionAlerts.jsx
botfront/imports/ui/components/stories/IntroStorySubMenu.jsx
botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/StoriesEditor.jsx
botfront/imports/ui/components/stories/StoryEditorContainer.jsx
botfront/imports/ui/components/stories/StoryTopMenu.jsx
botfront/imports/ui/components/stories/style.import.less

Exceptions (errors and warnings) can now be seen in:
- story group menu
- story top bar
- individual branch tabs
- ace editor

Exception handling

---

botfront/imports/api/instances/instances.methods.js
botfront/imports/lib/story.utils.js
botfront/imports/ui/layouts/project.jsx
cli/project-template/.botfront/docker-compose-template.yml

Three small fixes

---

botfront/docs/guide/deployment/README.md
botfront/docs/guide/deployment/credentials.md
botfront/docs/guide/deployment/endpoints.md
botfront/docs/guide/developers-guide/README.md
botfront/docs/guide/getting-started/cli.md
botfront/docs/guide/getting-started/quick-start.md
botfront/docs/guide/getting-started/setup.md
botfront/docs/guide/rasa/nlu/README.md
botfront/docs/guide/rasa/nlu/evaluation.md
botfront/docs/guide/rasa/nlu/training.md
botfront/docs/guide/rasa/nlu/training_adding_data.md
botfront/docs/guide/rasa/stories/README.md
botfront/docs/guide/rasa/stories/custom_actions.md

proofread and make small fixes on the docs

docs(branching): proofread and make small fixes

---

botfront/cypress/integration/stories/story_exceptions.spec.js

I changed the story_exceptions test as it was passing locally but not on CI
- this test now uses specific selectors to type in the story branch ace editors

fix: exception test failing after branching

---

botfront/imports/api/story/stories.collection.js
botfront/imports/ui/components/stories/StoriesContainer.jsx

all story of a projet are fetch in the StoryContainer and added to the context "ConversationOptionsContext"

feat: all story of a projet are fetch in the StoryContainer

---

.codeclimate.yml
botfront/imports/api/globalSettings/globalSettings.schema.default.js
botfront/imports/api/globalSettings/globalSettings.schema.docker-compose.js
botfront/imports/api/project/project.collection.js
botfront/imports/api/project/project.methods.js
botfront/imports/api/project/project.schema.default.js
botfront/imports/lib/story.utils.js
botfront/imports/lib/story_controller.tests.js
botfront/imports/ui/components/settings/DefaultDomain.jsx
botfront/imports/ui/components/settings/Settings.jsx
botfront/private/default-settings.docker-compose.ci.json
botfront/private/default-settings.docker-compose.dev.json
botfront/private/default-settings.docker-compose.json
botfront/private/default-settings.json

This adds a project specific default domain to be used as the basis for domain generation.

feat(default domain): declare default domain in project settings

---

botfront/imports/api/setup.js
botfront/server/migrations.js

chore(default domain): add migration

---

botfront/cypress/integration/stories/stories.spec.js
botfront/cypress/support/index.js
botfront/imports/api/story/stories.collection.js
botfront/imports/ui/components/common/ToolTipPopup.jsx
botfront/imports/ui/components/common/style.import.less
botfront/imports/ui/components/stories/BranchTabLabel.jsx
botfront/imports/ui/components/stories/StoriesContainer.jsx
botfront/imports/ui/components/stories/StoriesEditor.jsx
botfront/imports/ui/components/stories/StoryEditorContainer.jsx
botfront/imports/ui/components/stories/StoryTopMenu.jsx
botfront/imports/ui/components/stories/style.import.less
botfront/imports/ui/components/utils/Context.js

- Created the frontend for a warning message that displays when a story is connected to from another story
- Delete story button (trash icon) is disabled when the story has been connected to from another story

Checkpoint destination

---

botfront/imports/ui/components/stories/style.import.less

change color of branching tab to lighter ones

fix: improve branching tab color

---

botfront/imports/ui/components/example_editor/NLUExampleText.jsx
botfront/imports/ui/components/utils/UserUtteranceViewer.jsx

change the regex to match more characters,
also fix repeating non words characters in the UserUtteranceViewer
not possible to test selection with cypress

fix: tagging of accentuated characters

---

botfront/cypress/integration/stories/stories.spec.js
botfront/imports/ui/components/stories/StoryTopMenu.jsx

chore: remove story duplication and the related test

---

botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/imports/api/project/response.schema.js

fix: quick reply schema also add tests

---

botfront/imports/ui/components/common/StoryGroupItem.jsx

fix: storyGroup deletion was not available after a unlinking

---

botfront/imports/lib/story_controller.js

https://github.com/botfront/botfront/issues/236

fix: wrong slot properties

---

botfront/imports/ui/components/settings/DefaultDomain.jsx

- I added a message to default domain settings that explains what can be done there.
- I did not test this feature as it is a static text message

chore: add message to default domain settings

---

botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/api/project/project.methods.js

fix: can't fetch entities when an nlu example has no entities key

---

cli/project-template/.botfront/botfront.yml

chore: bump rasa ver

---

botfront/imports/api/importExport/export.methods.js
botfront/imports/api/importExport/import.methods.js
botfront/imports/ui/components/settings/ExportProject.jsx
botfront/imports/ui/components/settings/ImportProject.jsx
botfront/imports/ui/components/settings/style.import.less

- added default parameters to the export request (export as json)
- added optional parameters to the export request (export with conversations)
- fixed a error message typo when importing

feat: add options to project export

---

botfront/cypress/integration/stories/story_exceptions.spec.js

ensure that story is link before checking for warning should fix issues with the cloud build

fix: add check to ensure story is linked

---

botfront/cypress/integration/stories/stories.spec.js

a fix for the tests in the clould

fix: change self link test for the cloud build

---

botfront/imports/ui/components/stories/style.import.less

widen the story name input field

feat: widen the story name input field

---

.github/workflows/main.yml
botfront/package.json

This is supposed to run `npm run test-watch` every time a pr is made or a commit is pushed to master

automatic meteor test watch testing

---

botfront/cypress/integration/stories/story_exceptions.spec.js

check for branch existance in ui before trying to access them

fix: potential fix for the story exceptions

---

botfront/cypress/integration/stories/story_exceptions.spec.js

fixes for story exceptions tests

fix: storyexceptions test fixes

---

botfront/cypress/integration/stories/story_groups.spec.js

test: fix story groups

---

botfront/imports/api/nlu_model/nlu_model.schema.js

add cannonical field to training example schema

chore: add cannnonical field

---

api/routes/conversations.js
api/server/utils.js

support alwaystrusted and logUtterancesFromTracker

feat: add support for cli arguments

---

botfront/imports/api/project/response.methods.js

fix: no response duplication

---

botfront/imports/ui/components/settings/ImportProject.jsx
botfront/imports/ui/components/settings/style.import.less
botfront/package-lock.json
botfront/package.json

You can now choose what to export before importing a project

feat: choose export option

---

botfront/imports/ui/components/admin/settings/Settings.jsx
botfront/imports/ui/layouts/project.jsx

Two cool improvements

---

botfront/package-lock.json
botfront/package.json

Updated cypress, hopefully bringing more stability to testing

chore: updated cypress

---

botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/StoriesContainer.jsx

fix: fixed rasa parsing in visual story editor

---

botfront/cypress/integration/stories/default_story_group.spec.js

I added a slight delay so the page has time to update

fix: default story group is failing

---

botfront/imports/ui/components/nlu/activity/Activity.jsx

fix: deep links for conversation

---

botfront/cypress/integration/stories/visual_editor.spec.js
botfront/imports/ui/components/constants.json
botfront/imports/ui/components/stories/common/StoryVisualEditor.jsx
botfront/package-lock.json
botfront/package.json

Test nlu inference and remove parenthesis when no intents detected in the visual editor

test: nlu inference

---

api/routes/port_project.js
api/routes/port_project.test.js
botfront/package-lock.json

I removed the training object from projects on import and export.
I tested that the training object is removed when porting

fix: training state stuck in training after import

---

botfront/docs/guide/rasa/stories/custom_actions.md

chore: typo

---

botfront/imports/api/importExport/export.methods.js
botfront/imports/api/instances/instances.methods.js
botfront/imports/lib/story.utils.js

I fixed the domain.yml file of the export for rasa zip.
- response sequences are filtered based on the selected language and the language tag is removed.

refactor: exclude language in export for rasa

---

botfront/imports/ui/components/conversations/ConversationsBrowser.jsx

removes useless borders,
and removes all lang message

refactor: removes useless borders,

---

botfront/cypress/integration/01_initial_setup_dont_change_name/initial_setup.spec.js
botfront/package-lock.json
botfront/package.json

opened to trigger the github actions

test: removes callback might fix random bug

---

botfront/imports/ui/components/incoming/Incoming.jsx
botfront/imports/ui/components/nlu/models/NLUModel.jsx
botfront/imports/ui/components/stories/StoriesContainer.jsx
botfront/imports/ui/layouts/project.jsx

feat(project context): refresh intents and entities on mount

---

botfront/imports/api/importExport/import.methods.js

increases the file size limit for import files to 100mb

refactor: increase import file size limit

---

botfront/imports/ui/components/common/DataTable.jsx
botfront/imports/ui/components/incoming/style.import.less
botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/activity/ActivityActionsColumn.jsx
botfront/imports/ui/components/nlu/activity/style.import.less

New style for the buttons in new utterances 👨‍🎨

style: new utterances buttons

---

botfront/imports/ui/components/common/DataTable.jsx
botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/activity/ActivityInsertions.jsx

fix post-reparse mutation

---

botfront/imports/ui/components/conversations/ConversationDialogueViewer.jsx
botfront/imports/ui/components/example_editor/UserUtteredEventViewer.jsx
botfront/imports/ui/components/example_editor/style.import.less
botfront/imports/ui/components/nlu/common/style.import.less
botfront/imports/ui/components/utils/ExampleUtils.js

the conversations viewer shows confidence next to intent for a user utterance

refactor: include intent confidence score in conversations viewer

---

botfront/.meteor/packages
botfront/.meteor/versions
botfront/imports/startup/server/apollo.js
botfront/imports/ui/layouts/project.jsx
botfront/package-lock.json
botfront/server/startup.js

fix: meteor server setup up for graphQL subscriptions

---

botfront/docs/guide/misc/migration.md
botfront/imports/api/graphql/botResponses/schemas/botResponses.types.graphql
botfront/imports/api/graphql/common/common.types.graphql
botfront/imports/api/graphql/common/commonResolver.js
botfront/server/migrations.js
cli/project-template/.botfront/botfront.yml
cli/project-template/rasa/Dockerfile

chore: add migration to merge sequents

---

botfront/cypress/integration/incoming/new_utterances.spec.js
botfront/cypress/integration/nlu_models/canonical.spec.js
botfront/cypress/integration/nlu_models/nlu_intentmessage.spec.js
botfront/cypress/integration/stories/visual_editor/visual_editor.spec.js
botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/api/nlu_model/nlu_model.utils.js
botfront/imports/ui/components/nlu/common/IntentLabel.jsx
botfront/package-lock.json

The first example for an intent or an intent with a unique combination of entities will be marked canonical

feat: mark any first example for an intent & entity combination canonical

---

.github/workflows/main.yml

ci: don't rebuild docs on prerelease

---

.github/workflows/main.yml
botfront/cypress/fixtures/botfront_project_import.json

ci: overwrite artifacts

---

api/app.js
api/routes/conversations.js
botfront/imports/api/graphql/conversations/schemas/conversations.types.graphql
botfront/imports/ui/components/conversations/ConversationDialogueViewer.jsx
botfront/imports/ui/components/conversations/ConversationViewer.jsx
botfront/imports/ui/components/conversations/queries.js
botfront/imports/ui/components/example_editor/UserUtteredEventViewer.jsx

feat: userIds attached to conversation documents

---

.github/workflows/main.yml
botfront/cypress/integration/incoming/conversations_navigation.spec.js

ci: continue-on-error

---

api/routes/conversations.js

refactor: add intents/actions array at the root of each conversation

---

botfront/imports/lib/story_controller.js
botfront/imports/ui/components/nlu/common/IntentLabel.jsx
botfront/imports/ui/components/stories/common/StoryVisualEditor.jsx
botfront/imports/ui/components/stories/common/UserUtterancePopupContent.jsx

fix: bug with utterance insertion in visual story editor

---

.vscode/settings.json
botfront/docs/guide/getting-started/cli.md
cli/project-template/.botfront/docker-compose-template.yml
cli/project-template/actions/Dockerfile
cli/project-template/rasa/Dockerfile
cli/src/commands/services.js
cli/src/utils.js

`docker-compose.yml` and `.env` files are now generated at
the root of the project.
Images and versions are now taken from the `botfront.yml` and populated
in Dockerfile(s) for Rasa and Actions

feat(cli): improvements in version management and file generation

---

cli/project-template/.botfront/botfront.yml
cli/src/commands/init.js
cli/src/utils.js

Mongo databases initialized with botfront init are now protected with a username and a password. Authentication info can be found in the botfront.yml

feat(cli): mongo database security

---

botfront/client/main.less
botfront/imports/api/instances/instances.methods.js
botfront/imports/ui/components/nlu/activity/style.import.less
botfront/imports/ui/layouts/project.jsx

fix: strip slashes when parsing and no model trained

---

botfront/imports/api/graphql/botResponses/resolvers/nlgResolver.js

refactor: add metadata field to nlg resolver

---

botfront/imports/api/graphql/botResponses/resolvers/nlgResolver.js
botfront/imports/api/graphql/common/commonResolver.js
botfront/imports/ui/layouts/graphql.js
botfront/imports/ui/layouts/project.jsx
botfront/package-lock.json
botfront/package.json

any-validation

---

botfront/imports/ui/components/example_editor/style.import.less
botfront/package-lock.json

correct the alignment of the confidence score text in the conversation viewer.

fix: intent confidence alignment in conversations

---

botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/imports/ui/components/stories/common/BotResponsesContainer.jsx
botfront/imports/ui/components/stories/common/StoryVisualEditor.jsx
botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx

fix: bot response data mismatch in stories after closing the response editor

fix: missing response content in visual editor

---

botfront/imports/api/graphql/botResponses/mongo/botResponses.js
botfront/imports/api/graphql/nlu/mongo/statistics.js
botfront/imports/api/nlu_model/nlu_model.methods.js

refactor: add allowDiskUse for all aggregations

---

.github/workflows/main.yml
botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js
botfront/cypress/integration/bot_responses/quickreply_bot_response.spec.js
botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/ui/components/common/ToggleField.js
botfront/imports/ui/components/templates/MetadataForm.jsx

cause cypress tests to be marked as passed even if they're not

refactor: remove continue on error

---

botfront/cypress/integration/bot_responses/bot_response.spec.js

refactor: botresponse test fix

---

botfront/cypress/integration/bot_responses/custom_bot_response.spec.js

refactor: fix custom bot response test

---

botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/cypress/integration/nlu_models/canonical.spec.js

refactor: use an empty story for canonical tests

---

botfront/docs/guide/misc/migration.md
cli/project-template/.botfront/botfront.yml

chore: bump rasa version

---

api/routes/port_project.js
api/routes/port_project.test.js
botfront/imports/api/importExport/export.methods.js
botfront/imports/ui/components/settings/ExportProject.jsx
botfront/imports/ui/components/settings/style.import.less

Selective Export

---

botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/activity/ActivityActionsColumn.jsx
botfront/imports/ui/components/nlu/activity/ActivityInsertions.jsx

automatic reinterpretation ux

---

botfront/imports/ui/components/templates/templates-list/style.import.less

chore: response form take all the space of the modal

---

botfront/docs/guide/misc/migration.md
cli/src/cli.js
cli/src/commands/init.js
cli/src/commands/services.js
cli/src/utils.js
cli/test/utils.test.js

fix(cli): major version upgrade + migration guide

---

botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js

standardize the before each for bot_response_consistency test

refactor: beforeEach in response consistecy test

---

botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js

refactor: deleteProject to create project

---

botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js

refactor: bot response consistency test

---

botfront/imports/ui/components/stories/common/PayloadEditor.jsx
botfront/imports/ui/components/stories/common/UserUtterancePopupContent.jsx

fix: it was not posible to have more than one entity in payload editor

---

api/models/models.js

fix: metadata were lost at import, add the metadata model in the api

---

botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx

refactor: allow to save metadata on default defined botresponses

---

botfront/imports/ui/components/templates/MetadataForm.jsx

chore: use the custom select field in metadata form

---

botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx

refactor: removes the variations in the metadata tab

---

botfront/imports/ui/components/common/IconButton.jsx
botfront/imports/ui/components/stories/common/BotResponseContainer.jsx
botfront/imports/ui/components/stories/common/BotResponsesContainer.jsx
botfront/imports/ui/components/stories/common/style.import.less
botfront/imports/ui/components/templates/botResponse.utils.js
botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx
botfront/imports/ui/layouts/graphql.js

refactor: metadata icon is green if there is metadata

refactor: metadata icon color

---

botfront/imports/ui/components/templates/botResponse.utils.js
botfront/imports/ui/components/templates/botResponse.utils.test.js
botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx

- fix: can create empty responses on the bot responses page

fix: check response empty

---

botfront/imports/api/graphql/botResponses/resolvers/nlgResolver.js
botfront/imports/api/graphql/botResponses/schemas/botResponses.types.graphql
botfront/imports/api/graphql/conversations/mongo/conversations.js
botfront/imports/api/graphql/conversations/resolvers/conversationsResolver.js
botfront/imports/api/graphql/conversations/schemas/conversations.types.graphql
botfront/imports/ui/components/conversations/queries.js

conversations

---

botfront/server/logger.js
botfront/server/startup.js

add a log when the application start
it looks like this
`2020-02-20T19:45:03.189Z [info] : Botfront 0.19.3 started /server/startup.js`

refactor: add log on startup

---

botfront/imports/lib/utils.js

use the proper axios instance 

fix: axios with json was not logged

---

api/app.js
api/loggerConfig.js
botfront/docs/guide/deployment/installation.mdx
botfront/docs/guide/developers-guide/contributing.mdx
botfront/server/logger.js

add format in api logs typo fixes

chore: add format in api logs

---

botfront/server/startup.js

refactor: use require package json for version at startup

---

botfront/package-lock.json
botfront/package.json

chore: cypress update

---

api/routes/port_project.js

fix: don't overwrite namespace on import

---

botfront/cypress/integration/nlu_models/synonyms.spec.js
botfront/cypress/support/index.js
botfront/imports/api/graphql/activity/schemas/activity.types.graphql
botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/api/project/project.methods.js
botfront/imports/api/slots/slots.methods.js
botfront/imports/api/story/stories.collection.js
botfront/imports/api/story/stories.methods.js
botfront/imports/ui/components/nlu/activity/mutations.js
botfront/imports/ui/components/nlu/models/Statistics.jsx
botfront/imports/ui/layouts/project.jsx

chore: dead code removal

---

botfront/imports/api/storyGroups/storyGroups.collection.js
botfront/imports/api/user/user.methods.js
botfront/imports/startup/server/apollo.js
botfront/imports/ui/components/stories/StoryEditorContainer.jsx
botfront/imports/ui/components/stories/StoryTopMenu.jsx
cli/project-template/.botfront/botfront.yml

feat: graphql authentification for external consumers

---

botfront/cypress/integration/stories/stories.spec.js
botfront/cypress/integration/stories/story_exceptions.spec.js
botfront/imports/ui/components/templates/templates-list/style.import.less

style: trash appear on hover in responses editor

---

api/package-lock.json
api/package.json
botfront/package-lock.json
botfront/package.json

chore: mongoose version up

---

botfront/cypress/integration/nlu_models/data.import.spec.js
botfront/cypress/integration/stories/stories.spec.js
botfront/imports/ui/components/common/IconButton.jsx

chore: minor data-cy prop glitch fix

---

botfront/cypress/integration/nlu_models/nlu_intentmessage.spec.js
botfront/imports/ui/components/nlu/models/NluDataTable.jsx

refactor: improve consistency of nlu-intentmessage

---

botfront/docs/guide/deployment/installation.mdx
botfront/imports/api/graphql/config/config.types.graphql
botfront/imports/api/graphql/config/configResolver.js
botfront/imports/startup/server/apollo.js

add grapqhQL healthCheck endpoint

refactor: add graphQL healthcheck

---

botfront/imports/ui/components/project/ProjectSidebar.jsx
botfront/imports/ui/layouts/project.import.less

add version number at the bottom of the side bar

feat: display version number at the bottom of the sidebar

---

botfront/cypress/integration/nlu_tagging/nlu_tagging.spec.js
botfront/imports/ui/components/nlu/common/EntityDropdown.jsx

Blocked non ascii chars in entities

feat: block non ascii chars in entities

---

botfront/imports/lib/story.utils.js

fix: fix bug with linking

---

botfront/imports/api/core_policies.js
botfront/imports/api/storyGroups/storyGroups.methods.js
botfront/imports/lib/story.utils.js
botfront/imports/ui/components/common/style.import.less
botfront/imports/ui/components/nlu/models/NLUModel.jsx
botfront/imports/ui/components/nlu/models/settings/NLUPipeline.jsx
botfront/imports/ui/components/settings/CorePolicy.jsx
botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/StoryGroupNavigation.jsx
botfront/imports/ui/components/stories/StoryGroupTree.jsx
botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx
botfront/imports/ui/components/stories/hooks/useStoryGroupTree.js
botfront/imports/ui/components/stories/style.import.less
botfront/server/migrations.js

dnd-tree-smart-groups

---

botfront/imports/ui/components/stories/style.import.less

chore: opacity as decimal not %

---

botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js
botfront/cypress/integration/stories/story_exceptions.spec.js
botfront/imports/ui/components/stories/StoryGroupTree.jsx
botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx
botfront/imports/ui/components/stories/search/SearchBar.jsx

fix: scrolling to a story makes the story group browser top menu disappear
refactor: move scroll to story functionality to the story search bar

refactor: move scroll to story functionality to the story search bar

---

cli/src/commands/init.js
cli/src/commands/services.js
cli/src/utils.js

fix: mongo credentials are overwritten on update

---

botfront/cypress/integration/stories/story_exceptions.spec.js
botfront/cypress/integration/stories/story_tree_navigation.spec.js
botfront/cypress/support/index.js
botfront/cypress/support/story.commands.js
botfront/imports/api/story/stories.methods.js
botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/StoryEditorContainer.jsx
botfront/imports/ui/components/stories/StoryGroupTree.jsx
botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx

test: tests for new story navigation

---

README.md

updated docs based on info gleaned from chatting over issues
fixes #488 
fixes #489
purely documentation
added some docs on cli and troubleshooting
commented out this image for now, as I'm not sure it should just be deleted...

chore: update README remove docs add troubleshooting

---

botfront/imports/lib/importers/loadDomain.js
botfront/imports/lib/story.utils.js
botfront/imports/lib/story.utils.tests.js
botfront/imports/lib/story_controller.js
botfront/imports/lib/story_controller.tests.js
botfront/imports/ui/components/settings/ImportRasaFiles.jsx
botfront/imports/ui/components/settings/fileImporters.js
botfront/imports/ui/layouts/context.js

* rename templates to responses comply with new rasa data spec
* exclude built-in rasa actions from domain

rasa-actions-and-responses

---

botfront/imports/ui/components/account/ForgotPassword.jsx
botfront/imports/ui/components/account/Login.jsx
botfront/imports/ui/components/account/ResetPassword.jsx
botfront/imports/ui/components/nlu/common/style.import.less
botfront/imports/ui/layouts/account.jsx
botfront/imports/ui/layouts/project.jsx
botfront/imports/ui/layouts/setup.jsx
botfront/package-lock.json
botfront/package.json

https://app.asana.com/0/1167131762957882/1159482897481498/f
https://app.asana.com/0/1167131762957882/1159805328733382/f
https://app.asana.com/0/1167131762957882/1157578782860673/f

Add word break in utterance viewer; remove react-window-size

---

api/app.js
api/loggerConfig.js

refactor: add api startup message

---

botfront/cypress/integration/01_initial_setup_dont_change_name/initial_setup.spec.js
botfront/imports/startup/client/routes.jsx

access to /setup routes redirects to 403 if setup has is complete

chore: add a check for access to /setup

---

botfront/cypress/integration/nlu_models/canonical.spec.js
botfront/cypress/integration/stories/visual_editor/visual_branches.spec.js
cli/project-template/.botfront/botfront.yml

chore: rasa version bump

---

botfront/imports/ui/components/stories/StoriesPageMenu.jsx
botfront/imports/ui/components/stories/search/SearchBar.jsx
botfront/imports/ui/components/stories/search/style.import.less
botfront/imports/ui/components/stories/style.import.less
botfront/imports/ui/components/utils/Utils.jsx
botfront/imports/ui/components/utils/style.import.less
botfront/package-lock.json

refactor: search bar width

---

botfront/cypress/integration/nlu_models/canonical.spec.js
botfront/cypress/integration/stories/stories_search.spec.js
botfront/cypress/integration/stories/visual_editor/visual_branches.spec.js
botfront/cypress/integration/stories/visual_editor/visual_editor.spec.js
botfront/imports/ui/components/nlu/activity/style.import.less
botfront/imports/ui/components/stories/common/UserUtterancesContainer.jsx
botfront/imports/ui/components/stories/common/style.import.less

feat(visual story editor): add option to insert new disjunct from payload

---

cli/src/cli.js
cli/src/commands/services.js

Improved the process of updating a project

Remove images built locally on minor update

---

botfront/client/main.less
botfront/cypress/integration/stories/nlu_editor.spec.js
botfront/imports/ui/components/example_editor/NLUExampleTester.jsx
botfront/imports/ui/components/example_editor/NLUPlayground.jsx
botfront/imports/ui/components/nlu/models/style/style.import.less
botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/common/nlu_editor/NluModalContent.jsx

fix:  allow utterances to be added in the nlu modal without a connection to rasa
fix: nluDataTable icons are always shown (should be on hover with canonical always visible)
todo: refresh after canonical

refactor: fix nlu editor bugs

---

botfront/cypress/fixtures/botfront_project_import.json
botfront/cypress/fixtures/branch_link_project.json
botfront/imports/api/graphql/story/unit_tests/indexTestData.js
botfront/private/default-settings.docker-compose.ci.json
botfront/private/default-settings.docker-compose.dev.json
botfront/private/default-settings.docker-compose.json
botfront/private/default-settings.json

fix: entity doubling in data parsed from rasa

---

botfront/imports/api/graphql/story/mongo/stories.js

add case insensitivity for the NLU regex in the stories search function

fix: stories search algorithim

---

botfront/cypress/integration/stories/nlu_editor.spec.js
botfront/cypress/support/index.js

nlu editor test fixes

---

botfront/cypress/integration/stories/play_button.spec.js

chore: test consistency

---

botfront/cypress/integration/nlu_models/nlu_intentmessage.spec.js

test: improve nlu_intentmessage.spec

---

botfront/cypress/integration/stories/visual_editor/visual_editor.spec.js

refactor: visual_editor.spec temp fix

---

botfront/cypress/integration/import_export_project/export-rasa.spec.js

chore: fix export-rasa spec

---

botfront/cypress/integration/import_export_project/export-rasa.spec.js

Revert "chore: fix export-rasa spec"

---

botfront/imports/ui/components/example_editor/NLUPlayground.jsx
botfront/package-lock.json

examples can be added from the NLU editor modal without a trained model

fix: nlu modal parsing error

---

botfront/client/main.html

refactor: cleanup main html file

---

botfront/imports/api/graphql/botResponses/schemas/botResponses.types.graphql
botfront/imports/api/graphql/common/common.types.graphql
botfront/imports/api/graphql/common/commonResolver.js
cli/project-template/.botfront/botfront.yml

chore: decommission StringOrListOfStrings

---

botfront/imports/ui/components/conversations/ConversationDialogueViewer.jsx
botfront/imports/ui/components/conversations/ConversationViewer.jsx
botfront/imports/ui/components/conversations/utils.js
botfront/imports/ui/components/conversations/utils.test.data.json
botfront/imports/ui/components/conversations/utils.test.js

Goes with https://github.com/botfront/botfront-ee/pull/114

refactor: extract conversation parser

---

botfront/imports/ui/components/project/ProjectSidebar.jsx
botfront/imports/ui/layouts/project.import.less

make the version number copyable and visible to all users
https://app.asana.com/0/1170145499389908/1170347345760075

chore: version number: allow copy

---

botfront/imports/lib/story.utils.js
botfront/imports/ui/components/conversations/utils.js

Fixes https://github.com/botfront/botfront/issues/575 This replaces two instances of `object.story` with `object.story || ''` in addlinkCheckpoints.

fix: story access safety in addlinkCheckpoints

---

cli/src/cli.js

fix(cli): invoking botfront in a non project folder crashes

---

botfront/package-lock.json
botfront/package.json

chore: install perf_hooks, uninstall webpack, autoprefixer

---

botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/ui/components/conversations/ConversationViewer.jsx
botfront/imports/ui/components/conversations/ConversationsBrowser.jsx

https://app.asana.com/0/1170145499389908/1172373213237441/f
https://app.asana.com/0/1170145499389908/1172782275588880/f

fix: weird behaviour when deleting conversations ++ fix: prevent unlabeled examples

---

botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/cypress/integration/bot_responses/carousel_bot_response.spec.js
botfront/cypress/integration/bot_responses/image_bot_response.spec.js
botfront/cypress/support/response.commands.js
botfront/imports/ui/components/stories/common/ImageThumbnail.jsx
botfront/imports/ui/components/stories/common/Images.import.less
botfront/imports/ui/components/templates/templates-list/SequenceEditor.jsx
botfront/imports/ui/components/templates/templates-list/TemplatesTableItem.jsx

https://app.asana.com/0/1170145499389908/1173032198206417/f

chore: misc improvements to carousel styles

---

botfront/cypress/integration/stories/slots.spec.js
botfront/cypress/integration/stories/stories.spec.js
botfront/imports/ui/components/stories/StoryGroupTree.jsx
botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx
botfront/imports/ui/components/stories/style.import.less

https://app.asana.com/0/1170145499389908/1171909731251265/f
https://app.asana.com/0/1170145499389908/1120248537990103/f

style/fix-overellipsization ++ Select the first story (and open group) when opening stories

---

botfront/client/main.less
botfront/imports/ui/components/form_fields/ButtonSelectField.jsx
botfront/imports/ui/components/form_fields/import.style.less
botfront/imports/ui/components/templates/MetadataForm.jsx

refactor(metadata-form): replace dropdown select fields with button select fields

refactor(metadata-form): use button select field

---

botfront/cypress/integration/stories/play_button.spec.js

refactor: play button test

---

botfront/cypress/docker-compose.yml
botfront/cypress/integration/02_training/training.spec.js
botfront/cypress/integration/stories/stories.spec.js
botfront/cypress/integration/stories/story_tree_navigation.spec.js
botfront/cypress/support/index.js
botfront/cypress/support/story.commands.js

ci: add ipc: host to e2e container

---

botfront/cypress/integration/bot_responses/quickreply_bot_response.spec.js
botfront/cypress/support/response.commands.js
botfront/imports/api/graphql/botResponses/mongo/botResponses.js
botfront/imports/api/graphql/botResponses/resolvers/botResponsesResolver.js
botfront/imports/api/graphql/botResponses/resolvers/nlgResolver.js
botfront/imports/api/graphql/botResponses/schemas/botResponseFragmentTypes.json
botfront/imports/api/graphql/botResponses/schemas/botResponses.types.graphql
botfront/imports/lib/botResponse.utils.js
botfront/imports/lib/botResponse.utils.test.js
botfront/imports/ui/components/stories/common/BotResponseContainer.jsx
botfront/imports/ui/components/stories/common/BotResponsePopupContent.jsx
botfront/imports/ui/components/stories/common/BotResponsesContainer.jsx
botfront/imports/ui/components/stories/common/StoryVisualEditor.jsx
botfront/imports/ui/components/stories/common/style.import.less
botfront/imports/ui/components/templates/common/ButtonTypeToggle.jsx
botfront/imports/ui/components/templates/common/style.import.less
botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx
botfront/imports/ui/components/templates/templates-list/SequenceEditor.jsx
botfront/imports/ui/components/templates/templates-list/Templates.jsx
botfront/imports/ui/components/templates/templates-list/style.import.less
botfront/imports/ui/layouts/graphql.js
botfront/imports/ui/layouts/project.jsx
botfront/package-lock.json
botfront/package.json
botfront/server/migrations.js
cli/project-template/.botfront/botfront.yml

https://app.asana.com/0/1172906309462386/1172906309492385
related PR: https://github.com/botfront/rasa-webchat/pull/242 https://github.com/botfront/rasa-addons/pull/70

Feat: quick reply and button bot responses

---

botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/activity/ActivityCommandBar.jsx
botfront/imports/ui/components/nlu/common/IntentLabel.jsx
botfront/imports/ui/components/nlu/common/style.import.less

also implements Shift + Backspace shortcut to reset intent when intent dropdown is open

feat: batch reset intent

---

botfront/imports/api/instances/instances.methods.js
botfront/imports/lib/utils.js
botfront/imports/ui/components/utils/Errors.jsx
botfront/imports/ui/components/utils/TrainButton.jsx

also, format ECONNREFUSED axios errors.

refactor: unify error display mechanisms

---

cli/project-template/.botfront/botfront.yml

fix: updagraded rasa-for-botfront with disambiguation fix

---

botfront/imports/ui/components/common/DataTable.jsx
botfront/imports/ui/components/nlu/activity/Activity.jsx

fix: clear typename on activity update

---

botfront/imports/ui/components/nlu/activity/Activity.jsx

fix: entity tagging in activity screen

---

botfront/imports/lib/importers/loadStories.js
botfront/imports/ui/components/settings/ExportProject.jsx
botfront/imports/ui/components/settings/ImportProject.jsx
botfront/imports/ui/components/settings/ImportRasaFiles.jsx
botfront/imports/ui/components/settings/fileImporters.js
botfront/imports/ui/components/settings/fileReaders.js
botfront/imports/ui/components/stories/common/nlu_editor/NluModalContent.jsx

https://app.asana.com/0/1172906309462386/1173338470852937/f
E2E testing will come with follow up story deprecating old style import/export

feat: add option to erase existing data during import

---

botfront/imports/ui/components/nlu/common/UserUtteranceViewer.jsx

fix: intent dropdown not clickable on canonical example

---

botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx

fix: hide publish switch

---

botfront/cypress/integration/stories/visual_editor/visual_editor.spec.js
botfront/imports/ui/components/nlu/common/UserUtteranceViewer.jsx
botfront/imports/ui/components/stories/common/UserUtteranceContainer.jsx

fix: click on intent in dropdown had no effect in story visual editor

---

botfront/cypress/integration/stories/stories_search.spec.js
botfront/imports/ui/components/stories/search/SearchBar.jsx
botfront/package-lock.json

clicking on the eye icon for a selected story in the story search dropdown will now de-select the story if it is selected

refactor: stories search multiselect

---

botfront/imports/ui/components/stories/common/StoryVisualEditor.jsx

chore: new form labels

---

botfront/imports/api/graphql/trackerStore/mongo/trackerStore.js
botfront/imports/api/graphql/trackerStore/mongo/trackerStore.test.data.js
botfront/imports/api/graphql/trackerStore/mongo/trackerStore.test.js

refactor: tracker store createdAt fixes

---

botfront/.vscode/launch.json
botfront/imports/api/project/project.schema.js
botfront/imports/ui/components/settings/Credentials.jsx
botfront/imports/ui/components/settings/Endpoints.jsx
botfront/package.json

chore: remove more references to orchestrator

---

botfront/imports/ui/components/stories/common/StoryVisualEditor.jsx

fix: lost read only class

---

cli/src/cli.js
cli/src/commands/init.js
cli/src/utils.js

feat(cli): replaced --no-mongo-auth with --enable-mongo-auth

---

botfront/.meteor/packages
botfront/.meteor/versions
botfront/client/main.js
botfront/cypress/integration/stories/branches.spec.js
botfront/cypress/integration/stories/play_button.spec.js

refactor: removes jquery and blazes templates

---

botfront/imports/ui/components/templates/MetadataForm.ce.jsx
botfront/package-lock.json

useState for metadata instead of use a prop since it occasionally creates issues with typing (related to EE bug)

refactor: useState for the model in metadata form

---

botfront/client/main.less
botfront/imports/api/project/project.methods.js
botfront/imports/api/project/project.schema.js
botfront/imports/lib/utils.js
botfront/imports/startup/client/routes.jsx
botfront/imports/ui/components/nlu/models/NLUModel.jsx
botfront/imports/ui/components/stories/search/style.import.less
botfront/imports/ui/components/stories/style.import.less
botfront/imports/ui/components/utils/TrainButton.jsx
botfront/imports/ui/layouts/chat.demo.jsx

https://app.asana.com/0/1000996379802102/1179543585608425/f

feat(chat demo): dev chatbot made shareable via a link

---

botfront/cypress/fixtures/conversation_event_templates.json
botfront/cypress/integration/incoming/conversations_navigation.spec.js
botfront/cypress/support/index.js
botfront/imports/ui/layouts/project.import.less

replicate changes to conversation tests on EE

refactor: conversation tests

---

botfront/client/main.less
botfront/cypress/integration/02_training/training.spec.js
botfront/imports/api/project/project.methods.js
botfront/imports/lib/utils.js
botfront/imports/startup/client/routes.jsx
botfront/imports/ui/components/ErrorCatcher.jsx
botfront/imports/ui/components/example_editor/ExampleTextEditor.jsx
botfront/imports/ui/components/example_editor/NLUExampleTester.jsx
botfront/imports/ui/components/stories/StoryErrorBoundary.jsx
botfront/imports/ui/components/stories/common/ImageThumbnail.jsx
botfront/imports/ui/components/stories/style.import.less
botfront/imports/ui/components/utils/AceField.jsx
botfront/imports/ui/components/utils/CrashReportButton.jsx
botfront/imports/ui/components/utils/TrainButton.jsx

feat: error page with report buttons

---

botfront/imports/api/project/project.methods.js
botfront/imports/ui/layouts/chat.demo.jsx

fix: fix init payload for chat demo

---

botfront/cypress/integration/nlu_models/nlu_examples.spec.js
botfront/cypress/integration/nlu_models/nlu_models.spec.js
botfront/cypress/integration/project_settings/project.settings.info.spec.js
botfront/cypress/integration/stories/story_tree_navigation.spec.js
botfront/package-lock.json
botfront/package.json

chore: update semantic ui

---

api/server/searchIndex/searchIndexing.utils.js
api/server/searchIndex/test/searchIndexing.utils.test.js
botfront/cypress/integration/import_export_project/export-project.spec.js
botfront/cypress/integration/import_export_project/import-project.spec.js
botfront/cypress/integration/project_settings/misc_tab.spec.js
botfront/imports/api/globalSettings/globalSettings.methods.js
botfront/imports/ui/components/admin/settings/MigrationControl.jsx
botfront/imports/ui/components/admin/settings/Settings.jsx

add a rebuild search index button and a migration control section to the mic tab of more settings

refactor: search index rebuild, migration control

---

botfront/imports/lib/story.utils.js
botfront/imports/lib/story.utils.tests.js
botfront/imports/lib/story_controller.js
botfront/imports/ui/components/utils/AceField.jsx
botfront/private/defaults/private.dev.yaml
botfront/private/defaults/private.yaml
botfront/private/defaults/public.yaml

https://app.asana.com/0/1000996379802102/1181619597536521/f

fix: add trigger intents to domain

---

botfront/imports/ui/components/nlu/common/IntentLabel.jsx
botfront/imports/ui/components/nlu/common/UserUtteranceViewer.jsx
botfront/imports/ui/components/nlu/common/style.import.less

fix: always display create intent in intent label

---

botfront/imports/startup/client/routes.jsx

add routes in a compoment so it's consistent with ee

chore: add routes in a compoment so it's consistent with ee

---

botfront/imports/api/graphql/story/mongo/stories.js
botfront/imports/ui/components/admin/settings/Settings.jsx
botfront/imports/ui/components/stories/search/SearchBar.jsx

fixes the debouncing of the story search. Add a console log in the debounced method to check when it's called if you want to see if it works

fix: story search debouncing

---

botfront/imports/ui/components/stories/search/SearchBar.jsx

fixes a leak in the stories search bar component

fix: search bar event listener leak

---

botfront/cypress/integration/02_training/training.spec.js
botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/cypress/integration/stories/visual_editor/response_renaming.spec.js
botfront/imports/api/graphql/botResponses/botResponses.model.js
botfront/imports/api/graphql/botResponses/mongo/botResponses.js
botfront/imports/api/graphql/story/mongo/stories.js
botfront/imports/lib/botResponse.utils.js
botfront/imports/ui/components/stories/Context.js
botfront/imports/ui/components/stories/common/BotResponseName.jsx

<!-- description of what you achieved
- add a check to prevent response names from containing white space
- run the schema validators on update from the upsertResponse function

fix: check response names for whitespace

---

botfront/imports/ui/components/common/DataTable.jsx
botfront/imports/ui/components/nlu/common/IntentLabel.jsx

refactor: improve intent selector style

---

botfront/imports/ui/components/common/DataTable.jsx

fix: crash when openning incoming

---

botfront/cypress/integration/bot_responses/variations.spec.js
botfront/cypress/support/story.commands.js
botfront/imports/api/conversations.js
botfront/imports/api/graphql/activity/activity.model.js

refactor: index improvements

---

botfront/cypress/support/story.commands.js
botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx

refactor: possible fix for story nav

---

.github/workflows/probe-into-failure.yml
botfront/cypress/docker-compose-prober.yml
botfront/cypress/prober.sh

test: add workflow_dispatch to probe into cypress spec failure

---

api/models/models.js
api/routes/port_project.js
api/routes/port_project.test.js
botfront/imports/api/slots/slots.methods.js
botfront/imports/lib/importers/loadStories.js
botfront/imports/ui/components/settings/fileImporters.js
botfront/imports/ui/components/stories/Slots.jsx

https://app.asana.com/0/1000996379802102/1185291372432105/f

fix: dashboards are now exported/imported

---

.github/workflows/main.yml
.github/workflows/probe-into-failure.yml

ci: fix mounted models volume not existing

---

botfront/imports/ui/components/nlu/evaluation/IntentReport.jsx

the value for f1 and recall were inverted
also rename accuracy to  recall

fix: the value for f1 and recall were inverted

---

botfront/imports/ui/components/stories/StoryGroupTree.jsx

refactor: possible fix for Error with is expanded of undefined

---

botfront/cypress/integration/bot_responses/bot_response.spec.js
botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js
botfront/cypress/integration/import_export_project/export-project.spec.js
botfront/cypress/integration/import_export_project/import-project.spec.js
botfront/cypress/integration/language_dropdown/persist_working_language.spec.js
botfront/cypress/integration/nlu_models/data.import.spec.js
botfront/cypress/integration/nlu_models/nlu_models.spec.js
botfront/cypress/integration/project_settings/project.settings.info.spec.js
botfront/cypress/integration/stories/visual_editor/visual_editor.spec.js
botfront/cypress/support/index.js
botfront/cypress/support/response.commands.js
botfront/imports/startup/client/routes.jsx
botfront/imports/ui/components/admin/settings/Settings.jsx
botfront/imports/ui/components/project/ProjectSidebar.jsx
botfront/imports/ui/components/settings/Settings.jsx
botfront/imports/ui/layouts/chat.demo.jsx

feat: routes for individual settings pages

---

cli/src/commands/services.js
cli/src/utils.js

refactor: update docs links in the cli

---

botfront/cypress/integration/stories/visual_editor/response_renaming.spec.js
botfront/imports/api/instances/instances.methods.test.js
botfront/imports/api/instances/testData/nlu_model_chitchat.data.js

refactor: backport fix for the test getTrainingDataInRasaFormat 

---

botfront/private/defaults/private.yaml
botfront/private/defaults/public.yaml

Pipeline are a better basis for optimization. See https://botfront.io/blog/better-intent-classification-and-entity-extraction-with-diet-classifier-pipeline-optimization

change-default-pipeline

---

botfront/client/main.less
botfront/imports/api/instances/instances.methods.js
botfront/imports/ui/components/nlu/evaluation/EntityReport.jsx
botfront/imports/ui/components/nlu/evaluation/EntityReport.tests.js
botfront/imports/ui/components/nlu/evaluation/Evaluation.jsx
botfront/imports/ui/components/nlu/evaluation/IntentReport.jsx
botfront/imports/ui/components/nlu/evaluation/KeyMetrics.jsx
botfront/imports/ui/components/nlu/evaluation/PredictionTable.jsx
botfront/imports/ui/components/nlu/evaluation/ReportTable.jsx
botfront/imports/ui/components/synonyms/Gazette.jsx
cli/project-template/.botfront/botfront.yml

Fixes https://github.com/botfront/botfront/issues/682
:: https://app.asana.com/0/1000996379802102/1188526462487337/f

fix: display entity evaluation

---

botfront/imports/ui/layouts/chat.demo.jsx
botfront/private/defaults/private.dev.yaml
cli/project-template/.botfront/botfront.yml

fix(training): fix wrong language/model association

---

botfront/package-lock.json
botfront/package.json

However couldn't update package-lock.json since install fails locally on MacOS with "TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function"

chore: bump chromedriver

---

botfront/imports/ui/components/conversations/ConversationsBrowser.jsx
botfront/imports/ui/components/incoming/style.import.less
botfront/imports/ui/components/stories/common/ActionPopupContent.jsx

fix: fix bug with action popup disappearing onscroll

---

botfront/cypress/integration/bot_responses/bot_response_consistency.spec.js
botfront/imports/ui/components/common/IconButton.jsx
botfront/imports/ui/components/stories/common/BotResponsesContainer.jsx

https://app.asana.com/0/1000996379802102/1188153376777090

refactor: add confirm popup to delete response

---

botfront/imports/ui/layouts/project.jsx

fix: auto redirect to login when logged out

---

botfront/cypress/integration/stories/story_tree_navigation.spec.js
botfront/cypress/support/story.commands.js

story tree navigation was regularly failing while creating story groups / stories.
these changes are aimed at fixing that

test: create story groups programatically

---

botfront/cypress/integration/stories/branches.spec.js
botfront/imports/ui/components/stories/StoryEditorContainer.jsx

child branches attach to the parent story when the second last branch is deleted

Fix: concat story on branch delete

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: issue message

---

botfront/imports/ui/components/stories/common/EntityValueEditor.jsx

fix: advanced entity editing not possible in data table

---

botfront/imports/api/graphql/story/mongo/stories.js
botfront/imports/api/graphql/story/resolvers/storiesResolver.js
botfront/imports/api/graphql/story/schemas/stories.types.graphql
botfront/imports/api/graphql/story/unit_tests/storySearch.test.js
botfront/imports/ui/components/stories/search/SearchBar.jsx
botfront/imports/ui/components/stories/search/queries.js

- Ports minor changes from stories search from EE
- add cypress commands from ee

refactor: stories search changes from EE

---

.github/workflows/main.yml
Dockerfile
botfront/.meteor/packages
botfront/.meteor/versions

chore: save source maps to decode production stacks

---

botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/activity/ActivityActionsColumn.jsx
botfront/imports/ui/components/nlu/activity/ActivityCommandBar.jsx

chore: make outdated activity disabled

---

botfront/imports/api/graphql/examples/schemas/examples.types.graphql
botfront/imports/ui/components/example_editor/InsertNLU.jsx
botfront/imports/ui/components/nlu/models/API.jsx

Fixes https://github.com/botfront/botfront/issues/793

fix: return of confidence in NLU playground

---

botfront/imports/ui/components/common/DataTable.jsx
botfront/imports/ui/components/nlu/activity/style.import.less

fix: fix infinite scrolling stuck on Loading

---

botfront/cypress/integration/nlu_models/data.import.spec.js
botfront/imports/api/graphql/examples/mongo/examples.js
botfront/imports/ui/components/common/DataTable.jsx
botfront/imports/ui/components/common/DataTableRow.jsx
botfront/imports/ui/components/nlu/activity/Activity.jsx
botfront/imports/ui/components/nlu/models/NLUModel.jsx
botfront/imports/ui/components/nlu/models/NluTable.jsx

loading stuck
bad ordering of drafts vs non-drafts

fix: issues with NluTable

---

botfront/imports/api/graphql/examples/mongo/examples.js
botfront/imports/api/graphql/examples/schemas/examples.types.graphql
botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/ui/components/nlu/models/NLUModel.jsx
botfront/imports/ui/components/nlu/models/graphql.js
botfront/imports/ui/components/stories/common/nlu_editor/NluModalContent.jsx

refactor: include projectId when deleting examples

---

botfront/imports/api/instances/instances.methods.js
botfront/imports/lib/client.safe.utils.js

Fixes https://github.com/botfront/botfront/issues/810

fix: filter out null entity groups and roles at export time

---

botfront/cypress/integration/nlu_models/entities.spec.js
botfront/cypress/support/nlu.commands.js
botfront/imports/api/nlu_model/nlu_model.methods.js
botfront/imports/api/nlu_model/nlu_model.schema.js
botfront/imports/ui/components/nlu/common/EntityLabel.jsx
botfront/imports/ui/components/nlu/common/UserUtteranceViewer.jsx
botfront/imports/ui/components/nlu/models/settings/NLUPipeline.jsx
botfront/imports/ui/components/stories/common/EntityValueEditor.jsx
botfront/imports/ui/components/templates/templates-list/Templates.jsx
botfront/imports/ui/layouts/project.jsx

- add cypress tests for entities
- add non-whitespace mode to allow entities in languages that don't use whitespace

refactor: add non-whitespace mode for entities

---

botfront/package-lock.json
botfront/package.json

chore: bump eslint to get es2020 syntax

---

botfront/imports/api/graphql/project/fileImporters.js

Smart groups were deleted on project wipe during import

fix: prevent smart group wipe on import

---

botfront/imports/lib/importers/validateDomain.js

fix: fix import domains with forms as list of strings

---

cli/project-template/.botfront/botfront.yml

chore: rasa bump

---

botfront/imports/api/importExport/export.methods.js
botfront/imports/ui/components/utils/TrainButton.jsx

- Fix crash due to `fs.rmdir` call on non-empty dir.
- Fix bad commit href for ssh strings.
- Disallow git feature when instance is down.

fix: git feature

---

botfront/imports/ui/components/stories/StoryGroupTree.jsx

Fixes dangerous prop access in story group menu code.

fix: safety

---

botfront/cypress/integration/stories/test_stories.spec.js
botfront/imports/api/roles/roles_tests/subscriptionRoles.test.js
botfront/imports/api/story/stories.collection.js
botfront/imports/api/story/stories.methods.js
botfront/imports/ui/components/nlu/models/Statistics.jsx
botfront/imports/ui/components/project/ProjectChat.jsx
botfront/imports/ui/components/stories/Stories.jsx
botfront/imports/ui/components/stories/StoryGroupTree.jsx
botfront/imports/ui/components/stories/common/UserUtteranceContainer.jsx
botfront/imports/ui/components/stories/hooks/useStoryGroupTree.js

fixes for the issues in https://www.notion.so/godialogue/various-test_case-issues-9b9dc972ae764018b2a232c513df3e6e
associated with rasa PR https://github.com/botfront/rasa-for-botfront/pull/39

fix: test case issues

---

botfront/imports/ui/components/stories/Stories.jsx

fix: form were not displayed after an import

fix: form were not displayed after an import

---

botfront/private/defaults/private.dev.yaml
botfront/private/defaults/private.gke.yaml
botfront/private/defaults/private.yaml

chore: default policies 

---

botfront/cypress/fixtures/dummy-git-settings/bfconfig.yml
botfront/cypress/integration/roles/roles-admin.js
botfront/cypress/support/index.js
botfront/imports/api/importExport/export.methods.js
botfront/imports/api/project/project.collection.js
botfront/imports/api/project/project.methods.js
botfront/imports/api/project/project.schema.js
botfront/imports/api/roles/roles.js
botfront/imports/startup/client/routes.jsx
botfront/imports/ui/components/index.jsx
botfront/imports/ui/components/project/ProjectSidebar.jsx
botfront/imports/ui/components/settings/GitSettings.jsx
botfront/imports/ui/components/settings/ProjectInfo.jsx
botfront/imports/ui/components/settings/Settings.jsx
botfront/imports/ui/components/utils/TrainButton.jsx

Moves git settings to dedicated tab

refactor: moves git settings to dedicated tab

---

docs/guide/rasa/stories/conversation_builder.mdx
docs/guide/rasa/stories/getting_started.mdx

docs: minimal additions for rules

---

README.md
docs/guide/installation/migration.mdx

docs: improve readme and add migration info

---

botfront/imports/api/instances/instances.methods.js
botfront/imports/api/setup.js
botfront/private/defaults/private.yaml
botfront/server/migrations.js

The default credentials, instance, and endpoints were wrong leading to unreachable rasa and other issues.
updated the selection of the defaults/private.yml files so that the right defaults file was being used for the mode and orchestrator

fix: default endpoints, instance, and credentials

---

botfront/imports/api/project/project.methods.js
botfront/imports/ui/layouts/chat.demo.jsx
botfront/imports/ui/layouts/project.import.less

uses logo saved in project or logo saved in admin menu for demo pages

feat: use logos on demo

---

cli/project-template/.botfront/botfront.yml

chore: bump rbf to v2.3.3-bf.3

---

botfront/imports/startup/server/apollo.js

bypass authentication when querying for health status 

refactor: noauth for healthcheck

---

botfront/imports/lib/utils.js

add details of the error to post training webhook failures

refactor: improve training webhook error messages
