botfront/docs/guide/getting-started/quick-start.md
Docker for linux does not support host.docker.internal, we added a warning that explains the issue and link to the actual docker issue on Github
I made sure to
=> docs: warning for linux users

botfront/imports/ui/components/example_editor/EntityPopup.jsx, botfront/imports/ui/components/example_editor/NLUExampleTester.jsx, botfront/imports/ui/components/example_editor/NLUExampleText.jsx, botfront/imports/ui/components/example_editor/NLUPlayground.jsx
Entity popup is not available in the playground. This feature is not tested as it not possible to select text in cypress. Also altered some code for removing lint error
=> chore(entity-popup): Removed entity popup from playground

botfront/imports/api/project/project.schema.default.js
adds a custom function in the default project schema to check if characters used in the name of the projects are alphanumeric.
also adds an error message if characters are not alphanumeric.
related: #28
=> fix issue 28, allowed characters for project name in settings page

botfront/imports/ui/components/settings/ProjectInfo.jsx
Improved the setState and onChange method for the projectInfo component. In the onChange method, now it is verified that the language deleted is not the one in 'saved in the project'
=> fix(add-language): backspace cannot be used to remove a language

botfront/cypress/integration/03-stories/stories.spec.js, botfront/cypress/integration/nlu_models/trainbutton.spec.js, botfront/imports/api/project/project.methods.js, botfront/imports/api/project/project.methods.test.js, botfront/imports/api/slots/slots.methods.js, botfront/imports/api/story/stories.methods.js, botfront/imports/ui/components/utils/TrainButton.jsx, package-lock.json
This function extracts entities and intents from training data and the stories, which will be used by the Context API to pass values to the individual components
Test cases:
1. No stories present
2. common_examples empty in the training data
3. only one model present with multiple combination of entities
4. Multiple models with combination of multiple entities [no entities, same entity present at multiple places at different places, different entities present at different places]
=> feat(context-helper): add entities and intent generation function

botfront/cypress/integration/stories/default_story_group.spec.js, botfront/cypress/integration/stories/stories.spec.js, botfront/imports/ui/components/common/Browser.jsx, botfront/imports/ui/components/common/style.import.less, botfront/imports/ui/components/stories/IntroStoryMenu.jsx, botfront/imports/ui/components/stories/IntroStorySubMenu.jsx, botfront/imports/ui/components/stories/Stories.jsx, botfront/imports/ui/components/stories/style.import.less
- I moved the Intro Stories button in the stories group menu into a new file to
- I rearranged the Stories Group Menu to include the IntroStorySubMenu component below the add story button
- I removed the blue tip header when viewing story groups
- I fixed a bug where the selected story group in the story group menu was grey instead of blue
=> Move intro stories

botfront/cypress/integration/stories/story_exceptions.spec.js, botfront/imports/lib/story.utils.js, botfront/imports/lib/story_controller.js, botfront/imports/ui/components/common/Browser.jsx, botfront/imports/ui/components/stories/BranchTabLabel.jsx, botfront/imports/ui/components/stories/ExceptionAlerts.jsx, botfront/imports/ui/components/stories/StoriesEditor.jsx, botfront/imports/ui/components/stories/StoryEditorContainer.jsx, botfront/imports/ui/components/stories/StoryTopMenu.jsx
- fixed a bug where alerts were not removed when deleting the last story in intro stories 
I wrote tests that check if:
- error & warning alerts are added & removed to the story group menu tab, story top menu, and branch tab
- error & warning alerts are removed when a story is deleted
- error & warning alerts are removed when the last intro story is deleted
=> Exception handling

botfront/imports/lib/story_controller.js, botfront/imports/ui/components/stories/StoriesContainer.jsx, botfront/imports/ui/components/stories/StoryEditorContainer.jsx, botfront/imports/ui/components/utils/Context.js
Story controller now receives templates/responses which removes a frequent and incorrect warning message (Response was not found. Have you defined it)
I created a react context for the responses/templates
I added data to this context in stories container
I used data from this context in StoryEditorContainer
=> feat: add response context to StotyEditorContainer

botfront/imports/ui/components/nlu/evaluation/Evaluation.jsx
Fixes https://github.com/botfront/botfront/issues/244
=> fix: crash on null intent_evaluation result

botfront/cypress/integration/stories/story_exceptions.spec.js, botfront/imports/lib/story.utils.js, botfront/imports/lib/story_controller.js
Fixes Empty stories not training and removes no user utterance block warning in branches
=> fix: fixed empty stories not training

botfront/cypress/integration/stories/story_exceptions.spec.js
add another check before looking for warnings, should fix cloud build issues
=> fix: test destination story warning

botfront/imports/lib/story.utils.js
Allow training of empty stories and correctly displays name of errored stories
=> fix: train empty stories

api/app.js
fix: remove host information from the MongoDB connection failure message in the api
refactor: when connection fails, attempt to connect every second. Changed from no retry delay
=> fix: mongo connection failure message

botfront/imports/ui/components/conversations/ConversationsBrowser.jsx
fix: conversation page crash caused by tab being undefined after clicking incoming in the project sidebar while on the conversations page
=> fix: crash in incoming

botfront/server/migrations.js
so if the botResponse collection already exist it will not create issues with indexes
=> refactor: use update instead of insert for botResponse migrations

.vscode/settings.json, botfront/.vscode/launch.json, botfront/cypress/docker-compose.yml, botfront/imports/api/setup.js, botfront/package-lock.json, botfront/package.json, botfront/server/migrations.js
Since NODE_ENV can be overriden,
all occurences have been replaced with the
MODE env var name
=> refactor: use MODE instead of NODE_ENV

botfront/imports/ui/components/templates/templates-list/BotResponseEditor.jsx
renamed the metadata tab in the bot response editor to behaviour
=> refactor: rename metadata tab to behaviour

botfront/cypress/integration/nlu_models/nlu_examples.spec.js
- the test previously failed because one example was canonical and could not be deleted
=> refactor: nlu example test: expect one canonical

botfront/imports/startup/server/apollo.js
transfer the authorization header to the graphQL healthcheck call
=> refactor: use the authorization header in the healthcheck

botfront/imports/startup/server/apollo.js
Raises default request limit from 100 to 200kb. Also allows setting it with environment variable GRAPHQL_REQUEST_SIZE_LIMIT.
=> chore: raise graphql request size limit; expose env param

botfront/cypress/fixtures/branch_link_project.json, botfront/cypress/integration/stories/play_button.spec.js
The was three spaces instead of two before  
```- name: rasa_addons.nlu.components.gazette.Gazette\n ```
also update the pipeline so it uses the new DIETClassifier
=> refactor: pipeline correction for imported file in training tests

botfront/imports/api/graphql/trackerStore/schemas/trackerStore.types.graphql
fix https://github.com/botfront/botfront/issues/569
=> fix: missing environement field in the gql schema for trackerstore

botfront/cypress/plugins/index.js, botfront/cypress/support/index.js
Some cypress tests rely on a POST request to the graphql endpoint. It did not work if you had an API_KEY set up. This actually authenticates the cypress request using the usual mechanism.
=> refactor: use meteor authtoken to execute graphql query from cypress

botfront/imports/ui/components/stories/StoryGroupTreeNode.jsx
prevent lost of input when changing stories without an explicit blur of the bot response
=> refactor: save edited botresponses when unmounting

botfront/imports/ui/components/stories/common/UserUtteranceContainer.jsx, botfront/imports/ui/components/stories/common/UserUtterancesContainer.jsx
when editing a pending user utterance
- a click on a trash was saving the line and thus the nlu
- a click on a menu was also saving it
=> fix: nlu was saved when clicking on menus

botfront/imports/ui/components/utils/EntityUtils.js
duckling entities should not be saved in nlu data (from the playground)
add the following to the nlu-pipeline settings to enable duckling
>   - name: "DucklingHTTPExtractor"
>     url: "http://host.docker.internal:8000"
>     dimensions:
>       - number
>       - time
>     locale: "en_US"
>     timeout : 3
=> fix: do not save duckling entities

botfront/imports/ui/components/incoming/Incoming.jsx
Incoming did not load when the default language was not matching up with the nlu models available to the project.
=> fix: incoming when wrong default language in proje

botfront/cypress/integration/import_export_project/export-rasa.spec.js, botfront/imports/ui/components/stories/StoryGroupTree.jsx
only visible on ee
after adding a storygroup, the storygroup was before the pinned smartgroups
=> fix: pinned stories were not pinned at the top

botfront/imports/ui/components/stories/common/ImageThumbnail.jsx, botfront/public/images/image-temp.svg
hide Image not found icon when creating a image response
=> refactor: hide the image not found icon before setting the image

botfront/imports/ui/components/stories/common/BotResponsesContainer.jsx, botfront/imports/ui/layouts/project.jsx
hide copyFrom in the botresponse when there is one language
=> refactor: hide copyFrom in the botresponse when there is one language

botfront/imports/ui/components/nlu/evaluation/EntityReport.jsx, botfront/imports/ui/components/nlu/evaluation/Evaluation.jsx, botfront/imports/ui/components/nlu/evaluation/ReportTable.jsx
when there was no entities in the entity report it was crashing bf, use default value to prevent it
=> refactor: prevent entities report crash when empty

botfront/imports/api/graphql/botResponses/mongo/botResponses.js, botfront/imports/ui/components/common/StrictNumberInput.jsx, botfront/imports/ui/components/settings/fileImporters.js
Port a fix where bot response _id was an objectId instead of a string after domain import
port minor changes to domain file importers from EE
add the strict number input component
=> fix: rasa domain import (port from ee)

botfront/imports/ui/components/nlu/models/NLUModel.jsx
after adding chitchat examples the nlu data table was not updated with the newly added examples
=> fix: new chitchat examples were not displayed in the examples table

botfront/imports/ui/components/utils/CrashReportButton.jsx
https://reactjs.org/blog/2020/08/10/react-v17-rc.html#native-component-stacks
Until React 17, componentStack will be unhelpful in production. Best we can do is make sure top JS error location is dumped, as that one can be decoded using source map. This error location is first line of stack in dev, but second line is production, so we include first two lines.
=> feat: slightly better crash traces

botfront/imports/ui/components/nlu/common/EntityLabel.jsx, botfront/imports/ui/components/nlu/common/style.import.less
- entity names should only appear on hover
- entity names need a background to improve readability
=> style: only show entity names on hover

botfront/imports/api/endpoints/endpoints.methods.js
fix endpoints saving when the document does not exist
=> fix: endpoints saving when the document does not exist

botfront/cypress/integration/incoming/new_utterances.spec.js, botfront/imports/ui/components/nlu/activity/Activity.jsx, botfront/imports/ui/components/nlu/common/IntentLabel.jsx
autovalidate incoming utterances when changes are made
only happen if there is an intent set
=> refactor: autovalidate incoming utterances when changes are made

botfront/imports/api/graphql/botResponses/resolvers/nlgResolver.js, botfront/imports/lib/botResponse.utils.js, botfront/imports/ui/components/templates/common/CustomResponseEditor.jsx, botfront/imports/ui/components/templates/templates-list/SequenceEditor.jsx
- delete slot interpolation from the nlgResolver endpoint (moved to rasa)
- fix an issue working in custom responses where your progress would be overwritten after a few seconds of typing without saving
=> refactor: remove slot interpolation moved to rasa

botfront/imports/ui/components/ErrorCatcher.jsx, botfront/imports/ui/components/utils/CrashReportButton.jsx
incorrect setup for the Root url environment variable triggers a "failed to fetch" error, when this error occurs, provide a case specific error message.
=> refactor: specific error screen on failed to fetch

botfront/imports/api/graphql/botResponses/mongo/botResponses.js, botfront/imports/api/graphql/botResponses/resolvers/nlgResolver.js, botfront/imports/api/graphql/botResponses/schemas/botResponses.types.graphql, botfront/imports/lib/botResponse.utils.js, botfront/imports/lib/client.safe.utils.js, botfront/imports/lib/story.utils.js, botfront/imports/ui/layouts/graphql.js
This also phases out `template_type`, which no known Rasa channel uses.
=> chore: strict clean up of response payload before inserting in domain

botfront/imports/lib/story.utils.js, botfront/imports/lib/story.utils.tests.js, botfront/private/fixtures/project01-ee-ext/domain.yml, botfront/private/fixtures/project01/domain.yml
I added support for the key session_config in the extractDomain function.
Now when session_config is added to the default domain it will be included in the model thats passed to Rasa. 
Appears to work correctly with and without a session_config being included. When session_config is empty Rasa goes for its defaults which appears to be 60 mins in 2x.
=> feat(default domain): support session_config key in default domain.

botfront/imports/lib/utils.js
Related to issue #913. 
In the case you intend to add maxBodyLength to the axios.requestWithJsonBody I have made the change and created this pull request. 
This matches the maxContentLength length size of 400mb in order to resolve an issue where using the deployment feature does not work.
=> fix(axios requestWithJsonBody) add maxBodyLength to axios request

docs/guide/administration/roles.md
remove leftover mention of entreprise edition in the docs
=> fix(docs): remove botfront entreprise from docs
